### ISSUE TITLE
Los ejemplos de código no se muestran formateados como ```code```

### ISSUE THREAD

**Issue by matiasbaldanza** [altaskur/Apuntes#1]
En el markdown de GitHub, los bloques de código se delimitan entre tres backticks ``` code ```. 

¿Será esta la razón por la que el código no se muestra con el formato correspondiente en este ejemplo? (Que no es el único)
https://github.com/altaskur/Apuntes/wiki/js-SetInterval%28%29

![image](https://user-images.githubusercontent.com/55600/194044321-216413d4-57e7-4a39-b1da-c8f01ee89e63.png)

Referencia: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

Si luego tengo tiempo, hago un pull request con los cambios. Por ahora solo anuncio el problema. 😁

**Comment by altaskur** [comment]
Listo Arreglado!!! muchas gracias !

usando ```JavaScript y indicando el lenguaje creas la etiqueta correctamente
